import type { BrainGraph, BrainNode, BrainEdge } from "./graph-types";

// Mock data for initial D3 scaffold — will be replaced by live data

const nodes: BrainNode[] = [
  // Center
  {
    id: "mike",
    label: "Mike",
    domain: "center",
    type: "center",
    status: "good",
    urgency: 1,
    freshness: 1,
    summary: "Mike Ingersoll — Everything Abe knows",
  },

  // Domain nodes
  {
    id: "d-health",
    label: "Health",
    domain: "health",
    type: "domain",
    status: "attention",
    urgency: 0.7,
    freshness: 0.8,
    summary: "162 lab results, 20 medications, 8 providers",
    children: ["h-labs", "h-meds", "h-providers", "h-claims"],
  },
  {
    id: "d-finance",
    label: "Finance",
    domain: "finance",
    type: "domain",
    status: "good",
    urgency: 0.5,
    freshness: 0.9,
    summary: "FICO 836, 36 bills, $4,200/mo, 4% utilization",
    children: ["f-bills", "f-chase", "f-usaa", "f-credit"],
  },
  {
    id: "d-estate",
    label: "Estate",
    domain: "estate",
    type: "domain",
    status: "attention",
    urgency: 0.8,
    freshness: 0.7,
    summary: "Rogers active, Ingersoll closed. Year's Support pending.",
    children: ["e-rogers", "e-ingersoll", "e-opm"],
  },
  {
    id: "d-property",
    label: "Property",
    domain: "property",
    type: "domain",
    status: "attention",
    urgency: 0.6,
    freshness: 0.6,
    summary: "Home, RV (7 repairs), 2 vehicles, motorcycle",
    children: ["p-home", "p-rv", "p-hyundai", "p-palisade"],
  },
  {
    id: "d-personal",
    label: "Personal",
    domain: "personal",
    type: "domain",
    status: "critical",
    urgency: 0.9,
    freshness: 0.5,
    summary: "Will & POA MISSING. Divorce pending. VA transfer needed.",
    children: ["per-will", "per-divorce", "per-va"],
  },
  {
    id: "d-legal",
    label: "Legal",
    domain: "legal",
    type: "domain",
    status: "attention",
    urgency: 0.7,
    freshness: 0.6,
    summary: "Car accident settlement, hospital negligence case, divorce",
    children: ["l-accident", "l-hostle", "l-divorce"],
  },
  {
    id: "d-infra",
    label: "Infrastructure",
    domain: "infra",
    type: "domain",
    status: "good",
    urgency: 0.3,
    freshness: 1,
    summary: "All systems operational. 17 tasks, 12 active.",
    children: ["i-agents", "i-rag", "i-backup"],
  },
  {
    id: "d-comms",
    label: "Comms",
    domain: "comms",
    type: "domain",
    status: "good",
    urgency: 0.3,
    freshness: 1,
    summary: "Email, Telegram, iMessage, Calendar",
    children: ["c-email", "c-telegram", "c-calendar"],
  },

  // Health entities
  {
    id: "h-labs",
    label: "Lab Results",
    domain: "health",
    type: "entity",
    status: "attention",
    urgency: 0.7,
    freshness: 0.5,
    summary: "162 results. Some flagged high/low.",
  },
  {
    id: "h-meds",
    label: "Medications",
    domain: "health",
    type: "entity",
    status: "good",
    urgency: 0.4,
    freshness: 0.6,
    summary: "20 medications, active and historical.",
  },
  {
    id: "h-providers",
    label: "Providers",
    domain: "health",
    type: "entity",
    status: "neutral",
    urgency: 0.3,
    freshness: 0.5,
    summary: "8 healthcare providers on file.",
  },
  {
    id: "h-claims",
    label: "Insurance Claims",
    domain: "health",
    type: "entity",
    status: "attention",
    urgency: 0.6,
    freshness: 0.4,
    summary: "MVA BCBS claims, subrogation pending.",
  },

  // Finance entities
  {
    id: "f-bills",
    label: "Bills ($4,200/mo)",
    domain: "finance",
    type: "entity",
    status: "good",
    urgency: 0.5,
    freshness: 0.9,
    summary: "36 bills. 2 manual payments.",
  },
  {
    id: "f-chase",
    label: "Chase Accounts",
    domain: "finance",
    type: "entity",
    status: "good",
    urgency: 0.4,
    freshness: 0.8,
    summary: "Checking, Freedom Unlimited CC, Slate Edge CC.",
  },
  {
    id: "f-usaa",
    label: "USAA Accounts",
    domain: "finance",
    type: "entity",
    status: "good",
    urgency: 0.3,
    freshness: 0.7,
    summary: "Checking 8008, 1311. Savings 1303, 8016, 8615.",
  },
  {
    id: "f-credit",
    label: "FICO 836",
    domain: "finance",
    type: "entity",
    status: "good",
    urgency: 0.2,
    freshness: 0.9,
    summary: "Exceptional. Zero late payments. 4% utilization.",
  },

  // Estate entities
  {
    id: "e-rogers",
    label: "Rogers Estate",
    domain: "estate",
    type: "entity",
    status: "attention",
    urgency: 0.8,
    freshness: 0.7,
    summary: "ACTIVE. Year's Support pending. 9 creditors. OPM 7+ months.",
  },
  {
    id: "e-ingersoll",
    label: "Ingersoll Estate",
    domain: "estate",
    type: "entity",
    status: "good",
    urgency: 0.2,
    freshness: 0.8,
    summary: "CLOSED. Court orders signed Nov 2025.",
  },
  {
    id: "e-opm",
    label: "OPM/FERS Claim",
    domain: "estate",
    type: "entity",
    status: "critical",
    urgency: 0.9,
    freshness: 0.3,
    summary: "7+ months no response. Congressional inquiry needed.",
  },

  // Property entities
  {
    id: "p-home",
    label: "1603 Bobwhite Ct",
    domain: "property",
    type: "entity",
    status: "good",
    urgency: 0.3,
    freshness: 0.7,
    summary: "Bank OZK $751/mo. $93K remaining.",
  },
  {
    id: "p-rv",
    label: "RV Paradigm 2022",
    domain: "property",
    type: "entity",
    status: "attention",
    urgency: 0.6,
    freshness: 0.5,
    summary: "7 repairs pending. Lot: $352-426/mo.",
  },
  {
    id: "p-hyundai",
    label: "Hyundai (Mike)",
    domain: "property",
    type: "entity",
    status: "good",
    urgency: 0.3,
    freshness: 0.6,
    summary: "$659/mo. $10,983 remaining. 70% paid.",
  },
  {
    id: "p-palisade",
    label: "Palisade (Chrissy)",
    domain: "property",
    type: "entity",
    status: "attention",
    urgency: 0.5,
    freshness: 0.6,
    summary: "$737/mo. MVA settlement pending.",
  },

  // Personal entities
  {
    id: "per-will",
    label: "Will & POA",
    domain: "personal",
    type: "entity",
    status: "critical",
    urgency: 1,
    freshness: 0,
    summary: "NONE ON FILE. Critical gap.",
  },
  {
    id: "per-divorce",
    label: "Divorce",
    domain: "personal",
    type: "entity",
    status: "attention",
    urgency: 0.7,
    freshness: 0.5,
    summary: "NC attorney needed. Separation agreement signed.",
  },
  {
    id: "per-va",
    label: "VA Benefits",
    domain: "personal",
    type: "entity",
    status: "neutral",
    urgency: 0.4,
    freshness: 0.6,
    summary: "30% disability. Care transfer to Greenville needed.",
  },

  // Legal entities
  {
    id: "l-accident",
    label: "Car Accident Settlement",
    domain: "legal",
    type: "entity",
    status: "attention",
    urgency: 0.7,
    freshness: 0.5,
    summary: "$3K + $8K medical. Subrogation unresolved. DO NOT SIGN.",
  },
  {
    id: "l-hostle",
    label: "Hospital Negligence",
    domain: "legal",
    type: "entity",
    status: "attention",
    urgency: 0.6,
    freshness: 0.4,
    summary: "Jake Whitty, Hostle Law. Needs callback.",
  },
  {
    id: "l-divorce",
    label: "Divorce Legal",
    domain: "legal",
    type: "entity",
    status: "attention",
    urgency: 0.7,
    freshness: 0.5,
    summary: "NC or VA attorney needed. The Firm for Men considered.",
  },

  // Infra entities
  {
    id: "i-agents",
    label: "Agent System",
    domain: "infra",
    type: "entity",
    status: "good",
    urgency: 0.2,
    freshness: 1,
    summary: "7 VPs, 22 sub-agents. All healthy.",
  },
  {
    id: "i-rag",
    label: "Knowledge Engine",
    domain: "infra",
    type: "entity",
    status: "good",
    urgency: 0.3,
    freshness: 0.9,
    summary: "1,139 docs. 133K chunks. 99% coverage.",
  },
  {
    id: "i-backup",
    label: "Backups",
    domain: "infra",
    type: "entity",
    status: "good",
    urgency: 0.1,
    freshness: 1,
    summary: "Daily 3 AM. 8-rotation.",
  },

  // Comms entities
  {
    id: "c-email",
    label: "Email",
    domain: "comms",
    type: "entity",
    status: "good",
    urgency: 0.3,
    freshness: 1,
    summary: "Auto-filing every 4hrs. 5 accounts.",
  },
  {
    id: "c-telegram",
    label: "Telegram",
    domain: "comms",
    type: "entity",
    status: "good",
    urgency: 0.2,
    freshness: 1,
    summary: "Abe bot active. Alerts + briefings.",
  },
  {
    id: "c-calendar",
    label: "Calendar",
    domain: "comms",
    type: "entity",
    status: "good",
    urgency: 0.4,
    freshness: 1,
    summary: "30+ events next 30 days.",
  },
];

const edges: BrainEdge[] = [
  // Center to domains
  { source: "mike", target: "d-health", relationship: "domain", strength: 1 },
  { source: "mike", target: "d-finance", relationship: "domain", strength: 1 },
  { source: "mike", target: "d-estate", relationship: "domain", strength: 1 },
  { source: "mike", target: "d-property", relationship: "domain", strength: 1 },
  { source: "mike", target: "d-personal", relationship: "domain", strength: 1 },
  { source: "mike", target: "d-legal", relationship: "domain", strength: 1 },
  { source: "mike", target: "d-infra", relationship: "domain", strength: 1 },
  { source: "mike", target: "d-comms", relationship: "domain", strength: 1 },

  // Domain to entities
  { source: "d-health", target: "h-labs", relationship: "contains", strength: 0.8 },
  { source: "d-health", target: "h-meds", relationship: "contains", strength: 0.8 },
  { source: "d-health", target: "h-providers", relationship: "contains", strength: 0.8 },
  { source: "d-health", target: "h-claims", relationship: "contains", strength: 0.8 },

  { source: "d-finance", target: "f-bills", relationship: "contains", strength: 0.8 },
  { source: "d-finance", target: "f-chase", relationship: "contains", strength: 0.8 },
  { source: "d-finance", target: "f-usaa", relationship: "contains", strength: 0.8 },
  { source: "d-finance", target: "f-credit", relationship: "contains", strength: 0.8 },

  { source: "d-estate", target: "e-rogers", relationship: "contains", strength: 0.8 },
  { source: "d-estate", target: "e-ingersoll", relationship: "contains", strength: 0.8 },
  { source: "d-estate", target: "e-opm", relationship: "contains", strength: 0.8 },

  { source: "d-property", target: "p-home", relationship: "contains", strength: 0.8 },
  { source: "d-property", target: "p-rv", relationship: "contains", strength: 0.8 },
  { source: "d-property", target: "p-hyundai", relationship: "contains", strength: 0.8 },
  { source: "d-property", target: "p-palisade", relationship: "contains", strength: 0.8 },

  { source: "d-personal", target: "per-will", relationship: "contains", strength: 0.8 },
  { source: "d-personal", target: "per-divorce", relationship: "contains", strength: 0.8 },
  { source: "d-personal", target: "per-va", relationship: "contains", strength: 0.8 },

  { source: "d-legal", target: "l-accident", relationship: "contains", strength: 0.8 },
  { source: "d-legal", target: "l-hostle", relationship: "contains", strength: 0.8 },
  { source: "d-legal", target: "l-divorce", relationship: "contains", strength: 0.8 },

  { source: "d-infra", target: "i-agents", relationship: "contains", strength: 0.8 },
  { source: "d-infra", target: "i-rag", relationship: "contains", strength: 0.8 },
  { source: "d-infra", target: "i-backup", relationship: "contains", strength: 0.8 },

  { source: "d-comms", target: "c-email", relationship: "contains", strength: 0.8 },
  { source: "d-comms", target: "c-telegram", relationship: "contains", strength: 0.8 },
  { source: "d-comms", target: "c-calendar", relationship: "contains", strength: 0.8 },

  // Cross-domain connections (the magic — shows how things relate)
  { source: "h-claims", target: "l-accident", relationship: "related_to", strength: 0.6 },
  { source: "l-accident", target: "p-palisade", relationship: "vehicle_in", strength: 0.6 },
  { source: "per-divorce", target: "l-divorce", relationship: "legal_for", strength: 0.7 },
  { source: "e-rogers", target: "l-hostle", relationship: "lawsuit", strength: 0.6 },
  { source: "e-rogers", target: "e-opm", relationship: "benefit_claim", strength: 0.7 },
  { source: "p-home", target: "f-bills", relationship: "mortgage", strength: 0.5 },
  { source: "p-rv", target: "f-bills", relationship: "lot_lease", strength: 0.5 },
  { source: "p-hyundai", target: "f-bills", relationship: "loan_payment", strength: 0.5 },
  { source: "p-palisade", target: "f-bills", relationship: "loan_payment", strength: 0.5 },
];

export const MOCK_GRAPH: BrainGraph = {
  nodes,
  edges,
  metadata: {
    lastRefreshed: new Date().toISOString(),
    nodeCount: nodes.length,
    domainCounts: {
      health: nodes.filter((n) => n.domain === "health").length,
      finance: nodes.filter((n) => n.domain === "finance").length,
      estate: nodes.filter((n) => n.domain === "estate").length,
      property: nodes.filter((n) => n.domain === "property").length,
      personal: nodes.filter((n) => n.domain === "personal").length,
      legal: nodes.filter((n) => n.domain === "legal").length,
      infra: nodes.filter((n) => n.domain === "infra").length,
      comms: nodes.filter((n) => n.domain === "comms").length,
    },
    criticalCount: nodes.filter((n) => n.status === "critical").length,
    attentionCount: nodes.filter((n) => n.status === "attention").length,
  },
};
